# Generated by Django 3.1.1 on 2020-10-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('content', models.TextField(verbose_name='content')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment section',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=254, verbose_name='fullName')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=12, verbose_name='phoneNumber')),
                ('text', models.TextField(verbose_name='content')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUs',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='gategory of the news')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'gategory of the news',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='phoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, unique=True, verbose_name='phoneNumber')),
            ],
        ),
        migrations.CreateModel(
            name='sponsored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(blank=True, default='', max_length=250, verbose_name='Sponsored by')),
                ('img', models.ImageField(default='', upload_to='bidniTuhai', verbose_name='Sponsored picture')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('roleDesc', models.CharField(default='', max_length=250, null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('fb', models.URLField(default='', max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('profileImg', models.ImageField(upload_to='Users')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Сайтын Тохиргоо', editable=False, max_length=250)),
                ('facebook', models.URLField(blank=True, default='', verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, default='', verbose_name='twitter')),
                ('gmail', models.URLField(blank=True, default='', verbose_name='email')),
                ('email', models.EmailField(max_length=254, verbose_name='contactNumber')),
                ('phoneList', models.ManyToManyField(to='fesdemo.phoneNumber', verbose_name='phoneNumber')),
            ],
            options={
                'verbose_name': 'Configure',
                'verbose_name_plural': 'Configure of the website',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='site route')),
                ('newsImg', models.ImageField(upload_to='news', verbose_name='picture')),
                ('body', models.TextField(verbose_name='content')),
                ('featured', models.BooleanField(default=False, null=True, verbose_name='featured?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fesdemo.user', verbose_name='author')),
                ('categories', models.ManyToManyField(to='fesdemo.NewsCategory', verbose_name='gategory of the news')),
                ('comments', models.ManyToManyField(blank=True, to='fesdemo.Comment')),
            ],
            options={
                'verbose_name': 'News',
                'ordering': ('-created',),
            },
        ),
    ]
